const CANVAS_SIZE = 800;
const CANVAS_MARGIN = 25;
const RADIUS = (CANVAS_SIZE / 2) - CANVAS_MARGIN;
const TIME_FONT_SIZE = '16px';
const HOUR_PARTITION = 6;
const PARTITION_COUNT = 24 * HOUR_PARTITION;
const THETA = (Math.PI * 2) / PARTITION_COUNT;

export {
  CANVAS_SIZE, CANVAS_MARGIN, RADIUS, TIME_FONT_SIZE, HOUR_PARTITION, PARTITION_COUNT, THETA,
};
